version: "3.9"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "/opt/data/zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "/opt/data/kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "/opt/data/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=r00tr00t
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=bankAccount
    
  mongodb:
      image: mongo:5.0
      ports:
        - "27017:27017"
      volumes:
        - "/opt/data/mongodb:/data/db"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=r00tr00t

